name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

macro-paths: ["jaffle_shop/macros"]
model-paths: ["jaffle_shop/models"]
seed-paths: ["jaffle_shop/seeds"]
snapshot-paths: ["jaffle_shop/snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_project_evaluator', 'spark_utils', 'dbt_utils']
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false