jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: issues
      schema: main
      schema_directory: /Users/bonafide/Downloads/GitHub/fleetio/jaffle-shop-classic/scripts/data
      schemas_and_paths:
        main: /Users/bonafide/Downloads/GitHub/fleetio/jaffle-shop-classic/scripts/data